version: '3.8'

services:
  mysql:
    image: mysql:8.0
    network_mode: bridge
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: SANEM
      MYSQL_USER: donation-app
      MYSQL_PASSWORD: donation123*
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: donation-app123
      POSTGRES_USER: sanem-donation-app
      POSTGRES_DB: sanem
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8010:9010"

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16