version: '3.8'
name: sanem

services:
  db:
    image: postgres
    restart: no
    # set shared memory limit when using docker compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: donation-app123
      POSTGRES_USER: sanem-donation-app
      POSTGRES_DB: sanem
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - psg_sanem:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8010:9010"

volumes:
  psg_sanem:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16