USE SANEM;

CREATE TABLE CIDADE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIO (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(150) NOT NULL,
    login VARCHAR(150) NOT NULL,
    senha VARCHAR(150) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    email VARCHAR(50),
    fone VARCHAR(50),
    tipo VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    logradouro_tipo VARCHAR(255) NOT NULL,
    numero VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    active VARCHAR(50) NOT NULL,
    cod_cidade INT NOT NULL,
    FOREIGN KEY (cod_cidade) REFERENCES CIDADE(id)
);


CREATE TABLE BENEFICIARIO (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(150) NOT NULL,
    CPF VARCHAR(20),
    email VARCHAR(50),
    fone VARCHAR(50),
    tipo VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    bairro VARCHAR(255),
    logradouro VARCHAR(255),
    logradouro_tipo VARCHAR(255),
    numero VARCHAR(255),
    complemento VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    active VARCHAR(50) NOT NULL,
    observacao VARCHAR(500),
    cod_cidade INT NOT NULL,
    FOREIGN KEY (cod_cidade) REFERENCES CIDADE(id)
);

CREATE TABLE REGRA_ACESSO (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(150) NOT NULL
);

CREATE TABLE USUARIO_REGRA_ACESSO (
    USUARIO_ID INT NOT NULL,
    REGRA_ID INT NOT NULL,
    PRIMARY KEY (USUARIO_ID, REGRA_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(id),
    FOREIGN KEY (REGRA_ID) REFERENCES REGRA_ACESSO(id)
);

CREATE TABLE PRODUTO (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    tamanho VARCHAR(100) NOT NULL
);

CREATE TABLE DISTRIBUICAO (
    COD_USUARIO INT NOT NULL,
    COD_PRODUTO INT NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    quantidade INT NOT NULL,
    data DATETIME NOT NULL,
    PRIMARY KEY (COD_USUARIO, COD_PRODUTO),
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(id),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(id)
);

CREATE TABLE HISTORICO (
    COD_PRODUTO INT NOT NULL,
    COD_USUARIO INT NOT NULL,
    quantidade INT NOT NULL,
    tipo_movimento VARCHAR(2) NOT NULL,
    PRIMARY KEY (COD_PRODUTO, COD_USUARIO),
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(id),
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(id)
);

INSERT INTO SANEM.CIDADE (NOME) VALUES('CASCAVEL');

INSERT INTO SANEM.REGRA_ACESSO (nome) VALUES('SYS');
INSERT INTO SANEM.REGRA_ACESSO (nome) VALUES('ADMIN');
INSERT INTO SANEM.REGRA_ACESSO (nome) VALUES('GERENTE');
INSERT INTO SANEM.REGRA_ACESSO (nome) VALUES('ATENDENTE');

INSERT INTO SANEM.USUARIO (nome,login,senha,CPF,email,fone,tipo,UF,bairro,logradouro,logradouro_tipo,numero,complemento,status,active,cod_cidade) VALUES
	 ('SYSTEM','SYS','$2a$10$4a6gh/Y6S4t.N7S8a.gCZ.IELIdLFtiLa/U0GL9IsnaaY8TvtbZ3S','NOT','system@hotmail.com','NOT','SYSTEM','BR','NOT','NOT','NOT','NOT','NOT','ATIVO','TRUE',1);

INSERT INTO SANEM.USUARIO_REGRA_ACESSO (USUARIO_ID,REGRA_ID) VALUES(1,1);