spring:
  application:
    name: donation-app
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://db.jdryxbxnptnlbrhbhxbl.supabase.co:5432/postgres
      username: ${banco.username}
      password: ${banco.password}
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
        auto-commit: false
        maximum-pool-size: 5 #// TODO: AJUSTAR O POOL SIZE AND CONNECTION PER USER

api:
  security:
    token:
      secret: ${security.token}